import {
  EVENTS,
  MOTION,
  LOOKS,
  SOUND,
  CONTROLS,
  OPERATORS,
  VARIABLES,
} from '../../constants/BlockTypes';
import * as actionTypes from '../../constants/ActionTypes';

export const createDefaultSidebarBlocks = (initialBackdropId) => [
  { id: 'sidebar-move-x', type: MOTION, action: actionTypes.MOVE_X, value: 10 },
  { id: 'sidebar-move-y', type: MOTION, action: actionTypes.MOVE_Y, value: 10 },
  { id: 'sidebar-turn-right', type: MOTION, action: actionTypes.TURN_RIGHT, value: 15 },
  { id: 'sidebar-turn-left', type: MOTION, action: actionTypes.TURN_LEFT, value: 15 },
  { id: 'sidebar-goto', type: MOTION, action: actionTypes.GOTO, value: [0, 0] },
  { id: 'sidebar-goto-random', type: MOTION, action: actionTypes.GOTO_RANDOM, value: null },
  {
    id: 'sidebar-point-in-direction',
    type: MOTION,
    action: actionTypes.POINT_IN_DIRECTION,
    value: 90,
  },
  {
    id: 'sidebar-point-towards-random',
    type: MOTION,
    action: actionTypes.POINT_TOWARDS_RANDOM,
    value: null,
  },
  { id: 'sidebar-say', type: LOOKS, action: actionTypes.SAY, value: 'Hello!' },
  { id: 'sidebar-think', type: LOOKS, action: actionTypes.THINK, value: 'Hmm...' },
  {
    id: 'sidebar-say-timer',
    type: LOOKS,
    action: actionTypes.SAY_TIMER,
    value: { message: 'Hello!', duration: 2 },
  },
  {
    id: 'sidebar-think-timer',
    type: LOOKS,
    action: actionTypes.THINK_TIMER,
    value: { message: 'Hmm...', duration: 2 },
  },
  { id: 'sidebar-change-size-to', type: LOOKS, action: actionTypes.CHANGE_SIZE_TO, value: 100 },
  { id: 'sidebar-change-size-by', type: LOOKS, action: actionTypes.CHANGE_SIZE_BY, value: 10 },
  { id: 'sidebar-change-color', type: LOOKS, action: actionTypes.CHANGE_COLOR, value: '#FFAB19' },
  {
    id: 'sidebar-change-backdrop',
    type: LOOKS,
    action: actionTypes.CHANGE_BACKDROP,
    value: initialBackdropId,
  },
  { id: 'sidebar-hide', type: LOOKS, action: actionTypes.HIDE, value: null },
  { id: 'sidebar-show', type: LOOKS, action: actionTypes.SHOW, value: null },
  { id: 'sidebar-play-sound', type: SOUND, action: actionTypes.PLAY_SOUND, value: 'meow' },
  { id: 'sidebar-set-volume', type: SOUND, action: actionTypes.SET_VOLUME, value: 100 },
  {
    id: 'sidebar-change-volume-by',
    type: SOUND,
    action: actionTypes.CHANGE_VOLUME_BY,
    value: 10,
  },
  {
    id: 'sidebar-clear-all-sounds',
    type: SOUND,
    action: actionTypes.CLEAR_ALL_SOUNDS,
    value: null,
  },
  {
    id: 'sidebar-when-key-pressed',
    type: EVENTS,
    action: actionTypes.WHEN_KEY_PRESSED,
    value: 'Space',
  },
  {
    id: 'sidebar-when-sprite-clicked',
    type: EVENTS,
    action: actionTypes.WHEN_SPRITE_CLICKED,
    value: null,
  },
  {
    id: 'sidebar-when-backdrop-switches-to',
    type: EVENTS,
    action: actionTypes.WHEN_BACKDROP_SWITCHES_TO,
    value: initialBackdropId,
  },
  {
    id: 'sidebar-when-loudness-greater-than',
    type: EVENTS,
    action: actionTypes.WHEN_LOUDNESS_GREATER_THAN,
    value: 10,
  },
  {
    id: 'sidebar-when-i-receive',
    type: EVENTS,
    action: actionTypes.WHEN_I_RECEIVE,
    value: 'Hello!',
  },
  {
    id: 'sidebar-broadcast-message-for',
    type: EVENTS,
    action: actionTypes.BROADCAST_MESSAGE_FOR,
    value: 'Hello!',
  },
  { id: 'sidebar-wait-seconds', type: CONTROLS, action: actionTypes.WAIT_SECONDS, value: 1 },
  {
    id: 'sidebar-repeat-times',
    type: CONTROLS,
    action: actionTypes.REPEAT_TIMES,
    value: { times: 10 },
  },
  { id: 'sidebar-forever', type: CONTROLS, action: actionTypes.FOREVER, value: null },
  {
    id: 'sidebar-if-then',
    type: CONTROLS,
    action: actionTypes.IF_THEN,
    value: { condition: '' },
  },
  {
    id: 'sidebar-if-then-else',
    type: CONTROLS,
    action: actionTypes.IF_THEN_ELSE,
    value: { condition: '' },
  },
  {
    id: 'sidebar-wait-until',
    type: CONTROLS,
    action: actionTypes.WAIT_UNTIL,
    value: { condition: '' },
  },
  {
    id: 'sidebar-repeat-until',
    type: CONTROLS,
    action: actionTypes.REPEAT_UNTIL,
    value: { condition: '' },
  },
  {
    id: 'sidebar-operator-add',
    type: OPERATORS,
    action: actionTypes.OPERATOR_ADD,
    value: { left: '', right: '' },
  },
  {
    id: 'sidebar-operator-subtract',
    type: OPERATORS,
    action: actionTypes.OPERATOR_SUBTRACT,
    value: { left: '', right: '' },
  },
  {
    id: 'sidebar-operator-multiply',
    type: OPERATORS,
    action: actionTypes.OPERATOR_MULTIPLY,
    value: { left: '', right: '' },
  },
  {
    id: 'sidebar-operator-divide',
    type: OPERATORS,
    action: actionTypes.OPERATOR_DIVIDE,
    value: { left: '', right: '' },
  },
  {
    id: 'sidebar-operator-modulo',
    type: OPERATORS,
    action: actionTypes.OPERATOR_MODULO,
    value: { left: '', right: '' },
  },
  {
    id: 'sidebar-operator-less-than',
    type: OPERATORS,
    action: actionTypes.OPERATOR_LESS_THAN,
    value: { left: '', right: '' },
  },
  {
    id: 'sidebar-operator-equals',
    type: OPERATORS,
    action: actionTypes.OPERATOR_EQUALS,
    value: { left: '', right: '' },
  },
  {
    id: 'sidebar-operator-greater-than',
    type: OPERATORS,
    action: actionTypes.OPERATOR_GREATER_THAN,
    value: { left: '', right: '' },
  },
  {
    id: 'sidebar-operator-and',
    type: OPERATORS,
    action: actionTypes.OPERATOR_AND,
    value: { left: '', right: '' },
  },
  {
    id: 'sidebar-operator-or',
    type: OPERATORS,
    action: actionTypes.OPERATOR_OR,
    value: { left: '', right: '' },
  },
  {
    id: 'sidebar-operator-not',
    type: OPERATORS,
    action: actionTypes.OPERATOR_NOT,
    value: { operand: '' },
  },
  {
    id: 'sidebar-operator-join',
    type: OPERATORS,
    action: actionTypes.OPERATOR_JOIN,
    value: { left: '', right: '' },
  },
  {
    id: 'sidebar-operator-letter-of',
    type: OPERATORS,
    action: actionTypes.OPERATOR_LETTER_OF,
    value: { index: '', source: '' },
  },
  {
    id: 'sidebar-operator-length-of',
    type: OPERATORS,
    action: actionTypes.OPERATOR_LENGTH_OF,
    value: { source: '' },
  },
  {
    id: 'sidebar-operator-contains',
    type: OPERATORS,
    action: actionTypes.OPERATOR_CONTAINS,
    value: { source: '', target: '' },
  },
  {
    id: 'sidebar-operator-math-function',
    type: OPERATORS,
    action: actionTypes.OPERATOR_MATH_FUNCTION,
    value: { fn: 'abs', operand: '' },
  },
  {
    id: 'sidebar-operator-pick-random',
    type: OPERATORS,
    action: actionTypes.OPERATOR_PICK_RANDOM,
    value: { left: '', right: '' },
  },
  {
    id: 'sidebar-set-variable-to',
    type: VARIABLES,
    action: actionTypes.SET_VARIABLE_TO,
    value: { variableName: '', input: '' },
  },
  {
    id: 'sidebar-change-variable-by',
    type: VARIABLES,
    action: actionTypes.CHANGE_VARIABLE_BY,
    value: { variableName: '', amount: 1 },
  },
  {
    id: 'sidebar-add-to-list',
    type: VARIABLES,
    action: actionTypes.ADD_TO_LIST,
    value: { item: '', listName: '' },
  },
  {
    id: 'sidebar-delete-from-list',
    type: VARIABLES,
    action: actionTypes.DELETE_FROM_LIST,
    value: { index: 1, listName: '' },
  },
  {
    id: 'sidebar-delete-all-of-list',
    type: VARIABLES,
    action: actionTypes.DELETE_ALL_OF_LIST,
    value: { listName: '' },
  },
  {
    id: 'sidebar-insert-at-list',
    type: VARIABLES,
    action: actionTypes.INSERT_AT_LIST,
    value: { item: '', index: 1, listName: '' },
  },
  {
    id: 'sidebar-replace-item-in-list',
    type: VARIABLES,
    action: actionTypes.REPLACE_ITEM_IN_LIST,
    value: { index: 1, item: '', listName: '' },
  },
];
